### ISSUE TITLE
标题列名显示错误 %!d(string=size_bytes          )

### ISSUE THREAD

**Issue by itJoeSkyer** [fulldb/my2sql#3]
![image](https://github.com/fulldb/my2sql/assets/70500265/3019de65-880d-4f29-a455-226604e92bed)
最后一列，标题显示错误

**Comment by fulldb** [comment]
[32bee88](https://github.com/fulldb/my2sql/commit/32bee885e159beeb30035b6267bdb3528aa985d4)

**Comment by fulldb** [comment]
欢迎下载新版本再测试一下，已经修复 https://github.com/fulldb/my2sql/commit/32bee885e159beeb30035b6267bdb3528aa985d4
